---

- name: Common
  hosts: all
  become: yes
  roles:
    - common

- name: kubernetes
  hosts: kubernetes
  become: yes
  roles:
    - kubernetes

- name: ldap
  hosts: ldap
  become: yes
  roles:
    - ldap_auth

- name: Asterixk
  hosts: asterisk
  become: yes
  roles:
    - asterisk

- name: bgp_bird
  hosts: bgp_bird
  become: yes
  roles:
    - bgp_bird
