---

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
