---

- name: Install base packages
  apt:
    name: "{{ base.debian_packages }}"
    state: latest

#- name: Makes sure nftables is enabled
#  service:
#    name: nftables
#    enabled: yes
#  when: kubernetes_master is undefined

- name: Create user
  user:
    create_home: yes
    append: yes
    state: "{{ item.state }}"
    groups: sudo
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    password: "{{ item.user_password }}"
    update_password: always
  loop: "{{ active_users }}"

- name: Install caddy for LE
  apt:
    name: "caddy"
    state: latest

#- name: Copy base nftables if does not exist
#  template:
#    src: nftables.conf
#    dest: "/etc/nftables.conf"
#    force: no
#    owner: root
#    group: root
#    mode: "u=rw,g=rx,o=rx"
#  when: kubernetes_master is undefined
#
#- name: Add the firewall rule for ssh
#  lineinfile:
#    insertafter: "chain input {"
#    regexp: "^tcp dport {{ ansible_port }}*"
#    line: "tcp dport {{ ansible_port }} accept comment \"Accept ssh connection\""
#    path: /etc/nftables.conf
#  notify:
#    - Restart nftables
#  when: kubernetes_master is undefined
- name: Change timezone to UTC
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/Etc/UTC"
    dest: "/etc/localtime"
    state: link

# Set Up zabbix
- name: create the /etc/zabbix directory
  ansible.builtin.file:
    path: /etc/zabbix
    mode: u+rw,g+wx,o-rwx
    owner: zabbix
    group: zabbix
    recurse: yes
  notify:
    - Restart zabbix_agent
