---

- name: Install base packages
  yum:
    name: "{{ base.fedora_packages }}"
    state: latest

- name: Create user and add it to the sudo group (wheel)
  user:
    create_home: yes
    append: yes
    state: "{{ item.state }}"
    groups: wheel
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    password: "{{ item.user_password }}"
    update_password: always
  loop: "{{ active_users }}"

- name: Install caddy for LE
  yum:
    name: "caddy"
    state: latest

- name: Change timezone to UTC
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/Etc/UTC"
    dest: "/etc/localtime"
    state: link

# Set Up zabbix
- name: create the /etc/zabbix directory
  ansible.builtin.file:
    path: /etc/zabbix
    mode: u+rw,g+wx,o-rwx
    owner: zabbix
    group: zabbix
    recurse: yes
  notify:
    - Restart zabbix_agent
