---

- name: Install base packages
  community.general.openbsd_pkg:
    name: "{{ base.openbsd_packages }}"
    state: latest

- name: Create user
  user:
    create_home: yes
    append: yes
    state: "{{ item.state }}"
    groups: wheel
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/sh') }}"
    password: "{{ item.user_password }}"
    update_password: on_create
  loop: "{{ active_users }}"

# Set Up zabbix
- name: create the /etc/zabbix directory
  ansible.builtin.file:
    path: /etc/zabbix
    mode: u+rw,g+wx,o-rwx
    owner: _zabbix
    group: _zabbix
    recurse: yes
  notify:
    - Restart zabbix_agent
